# Generated by Django 4.1.5 on 2023-01-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComUser',
            new_name='Company',
        ),
    ]
