# Generated by Django 4.1.5 on 2023-01-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_comuser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('studentEmail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
