# Generated by Django 4.1.5 on 2023-01-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_studentuser_user_delete_companyuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internTitle', models.CharField(max_length=100)),
                ('companyAddress', models.CharField(max_length=200)),
                ('internshipDescription', models.CharField(max_length=500)),
                ('comName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('tPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
